name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The runner machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out the repository

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Define the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build the Application
        run: npm run build

  deploy:
    needs: build  # Run this job after 'build' completes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
            cd /path/to/project
            git pull origin main
            npm install --production
            pm2 restart app
          EOF
